import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, Layout, Menu, theme } from "antd";
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  HomeOutlined,
  KeyOutlined,
  RobotOutlined,
} from "@ant-design/icons";
import { ReactNode, useState } from "react";
import React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { signOut, useSession } from "next-auth/react";

const { Header, Sider, Content } = Layout;

export default function RootLayout({ children }: { children: ReactNode}): JSX.Element {
  const [collapsed, setCollapsed] = useState(true);
  const {
    token: { colorBgContainer },
  } = theme.useToken();
  const router = useRouter();
  const { status, data } = useSession();


  return (
    <div className={styles.app}>
      <Head>
        <title>Password Safe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Sider trigger={null} collapsible collapsed={collapsed}>
          <div className={styles.logo} />
          <Menu
            theme="dark"
            mode="inline"
            defaultSelectedKeys={[router.pathname]}
            selectable={status !== "unauthenticated"}
            disabled={status === "unauthenticated"}
            items={[
              {
                key: "/",
                icon: <HomeOutlined />,
                label: <Link href="/">Home</Link>,

              },
              {
                key: "/safe",
                icon: <KeyOutlined />,
                label: <Link href="/safe">Password Safe</Link>,
              },
              {
                key: "/generate",
                icon: <RobotOutlined />,
                label: <Link href="/generate">Generate Password</Link>,
              }
            ]}
          />
        </Sider>
        <Layout
          style={{
            height: "100vh",
          }}
        >
          <Header style={{ padding: 0, background: colorBgContainer, display: "flex", alignItems: "center" }}>
            {collapsed ? (
              <MenuUnfoldOutlined
                className={styles.trigger}
                onClick={() => setCollapsed(!collapsed)}
              />
            ) : (
              <MenuFoldOutlined
                className={styles.trigger}
                onClick={() => setCollapsed(!collapsed)}
              />
            )}
            {status === "authenticated" && (
                <Button onClick={() => signOut()} type="text" style={{marginLeft: "auto", marginRight: "20px"}}>{"Sign out as " + data.user?.name }</Button>
            )}
          </Header>
          <Content
            style={{
              height: "100%",
              margin: "24px 16px",
              padding: 24,
              minHeight: 280,
              backgroundColor: colorBgContainer,
            }}
          >
            {children}
          </Content>
        </Layout>
      </Layout>
    </div>
  );
}
