import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Layout, Menu, theme, Typography } from "antd";
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  HomeOutlined,
  KeyOutlined,
} from "@ant-design/icons";
import { ReactNode, useState } from "react";
import React from "react";

const { Header, Sider, Content } = Layout;
const { Title } = Typography;

export default function RootLayout({ children }: { children: ReactNode}) {
  const [collapsed, setCollapsed] = useState(false);
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <div className={styles.app}>
      <Head>
        <title>Password Safe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Sider trigger={null} collapsible collapsed={collapsed}>
          <div className={styles.logo} />
          <Menu
            theme="dark"
            mode="inline"
            defaultSelectedKeys={["1"]}
            items={[
              {
                key: "1",
                icon: <HomeOutlined />,
                label: "Home",
              },
              {
                key: "2",
                icon: <KeyOutlined />,
                label: "Password Safe",
              },
            ]}
          />
        </Sider>
        <Layout
          style={{
            height: "100vh",
          }}
        >
          <Header style={{ padding: 0, background: colorBgContainer }}>
            {collapsed ? (
              <MenuUnfoldOutlined
                className={styles.trigger}
                onClick={() => setCollapsed(!collapsed)}
              />
            ) : (
              <MenuFoldOutlined
                className={styles.trigger}
                onClick={() => setCollapsed(!collapsed)}
              />
            )}
          </Header>
          <Content
            style={{
              height: "100%",
              margin: "24px 16px",
              padding: 24,
              minHeight: 280,
              backgroundColor: colorBgContainer,
            }}
          >
            {children}
          </Content>
        </Layout>
      </Layout>
    </div>
  );
}
